import { ChatGroq } from '@langchain/groq';
import { StructuredOutputParser } from '@langchain/core/output_parsers';
import { z } from 'zod';
import dotenv from 'dotenv';

dotenv.config();

// 1. Define our strict Zod schemas
const QuestionSchema = z.object({
    text: z.string().describe("The text of the question"),
    difficulty: z.enum(["Easy", "Moderate", "Hard"]).describe("Difficulty level"),
    marks: z.number().describe("Marks allocated")
});

const SectionSchema = z.object({
    title: z.string().describe("e.g., Section A: Short Answers"),
    instruction: z.string().describe("Instructions for this section"),
    questions: z.array(QuestionSchema).describe("Array of questions in this section")
});

// CRITICAL FIX: Wrap the sections in a parent object. LLMs fail when asked for raw arrays.
const PaperSchema = z.object({
    sections: z.array(SectionSchema).describe("The generated sections containing all questions")
});

// 2. Create the robust LangChain parser
const parser = StructuredOutputParser.fromZodSchema(PaperSchema);

// 3. Initialize the Model
const model = new ChatGroq({
    apiKey: process.env.GROQ_API_KEY,
    model: 'llama-3.3-70b-versatile',
    temperature: 0.1, 
});

export const generateQuestionPaper = async (promptData: any) => {
    const { questionTypes, totalQuestions, totalMarks, additionalInstructions } = promptData;

    // 4. Extract the exact formatting instructions generated by Zod
    const formatInstructions = parser.getFormatInstructions();

    const prompt = `
    You are an expert AI teacher's assistant. Generate a structured question paper.
    
    Requirements:
    - Total Questions: ${totalQuestions}
    - Total Marks: ${totalMarks}
    - Question Types: ${questionTypes.join(', ')}
    - Additional Instructions: ${additionalInstructions || 'None'}
    
    Instructions:
    1. Group the questions into logical sections based on the requested types.
    2. Assign a difficulty (Easy, Moderate, or Hard) to each question.
    3. Ensure the sum of all question marks equals exactly ${totalMarks}.

    ${formatInstructions}
    `;

    try {
        console.log("🧠 Sending parser-injected prompt to Groq...");
        
        // 5. Get raw text from the LLM
        const response = await model.invoke(prompt);
        
        // 6. Force the parser to extract and validate the JSON object
        const parsedData = await parser.parse(response.content as string);
        
        console.log("✅ Groq Output successfully parsed!");
        
        // 7. RETURN ONLY THE ARRAY so it perfectly matches your MongoDB schema
        return parsedData.sections;

    } catch (error) {
        console.error('LangChain Parser Error:', error);
        throw new Error('Failed to generate structured paper from AI');
    }
};